# Site settings
title: ClouDesire
subtitle: Knowledge-Base
email: dev@cloudesire.com
description: "Official documentation for ClouDesire"
baseurl: ""
url: "http://docs.cloudesire.com" # the base hostname & protocol for your site
twitter_username: cloudesire
github_username:  cloudesire
github_edit_link: https://github.com/ClouDesire/cloudesire.github.io/edit/master
google_analytics_id: UA-58577492-1
highlighter: pygments
exclude: [ 'jenkins.sh', 'Gemfile*', 'jekyll-cloudfiles-upload' ]

# Build settings
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge

gems:
- jemoji
- jekyll-sitemap
