# Site settings
title: ClouDesire
subtitle: Knowledge-Base
email: dev@cloudesire.com
description: "Official documentation for ClouDesire and ThreeHops"
baseurl: ""
url: "http://docs.cloudesire.com" # the base hostname & protocol for your site
twitter_username: cloudesire
github_username:  cloudesire
highlighter: pygments
exclude: [ 'jenkins.sh', 'Gemfile*', 'jekyll-cloudfiles-upload' ]

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
- jemoji
- jekyll-sitemap
